Repository aws-amplify/amplify-cli, pull requests merged in 2020-12, with the labels that each got.

#5797 fix(amplify-appsync-simulator): utils.toJson false value
  packages/amplify-appsync-simulator/src/__tests__/velocity/util/general-utils.test.ts
  packages/amplify-appsync-simulator/src/velocity/util/general-utils.ts
Labels: pending-review

#6095 fix(graphql-transformer-core): fix gsi mutate san check
  packages/amplify-e2e-tests/schemas/migrations_key/four_gsi_model_schema.graphql
  packages/amplify-e2e-tests/schemas/migrations_key/three_gsi_model_schema.graphql
  packages/amplify-e2e-tests/src/__tests__/migration/api.key.migration2.test.ts
  packages/graphql-transformer-core/src/util/sanity-check.ts
Labels: graphql-transformer

#6096 fix: #6067 - nodejs mock return error from lambda
  packages/amplify-appsync-simulator/src/__tests__/velocity/index.test.ts
  packages/amplify-appsync-simulator/src/velocity/index.ts
  packages/amplify-nodejs-function-runtime-provider/src/utils/execute.ts
  packages/amplify-nodejs-function-runtime-provider/src/utils/invoke.ts
Labels: mock

#6094 chore: Added FF to facilitate Modelgen Migration
  packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/utils/auth-defaults-appliers.test.ts
  packages/amplify-cli-core/src/feature-flags/featureFlags.ts
  packages/amplify-codegen/package.json
  packages/amplify-codegen/src/commands/models.js
  packages/amplify-codegen/src/utils/getCodegenPackage.js
  packages/amplify-codegen/src/utils/index.js
  packages/amplify-codegen/tests/utils/getCodegenPackage.test.js
  yarn.lock
Labels: code-gen

#5808 feat(cli): generate REAMDE file in amplify dir
  packages/amplify-cli-core/src/state-manager/pathManager.ts
  packages/amplify-cli/src/__tests__/extensions/amplify-helpers/docs-manager.test.ts
  packages/amplify-cli/src/extensions/amplify-helpers/docs-manager.ts
  packages/amplify-cli/src/init-steps/s9-onSuccess.ts
Labels: pending-review
