Repository aws-amplify/amplify-cli, pull requests merged in 2022-09, with the labels that each got.

#10960 feat: show warning when the cloud backend build dir does not match local backend build dir
  packages/amplify-provider-awscloudformation/src/__tests__/utils/auto-updates.test.ts
  packages/amplify-provider-awscloudformation/src/push-resources.ts
  packages/amplify-provider-awscloudformation/src/utils/auto-updates.ts
Labels: do-not-merge

#10577 fix: updated roleName in show auth ACM helper to include the groupClaim
  packages/amplify-cli/src/__tests__/extensions/amplify-helpers/show-auth-acm.test.ts
  packages/amplify-cli/src/extensions/amplify-helpers/show-auth-acm.ts
Labels: first-time-contributor

#11074 fix: Await Metadata file updates to avoid race conditions
  .circleci/config.base.yml
  packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/amplify-meta-updaters.ts
  packages/amplify-cli-core/src/types.ts
  packages/amplify-provider-awscloudformation/src/push-resources.ts
  packages/amplify-provider-awscloudformation/src/resource-package/resource-packager.ts
Labels: run-e2e
