Repository aws-amplify/amplify-cli, pull requests merged in 2022-08, with the labels that each got.

#10667 feat!: hooks are no longer maintained in the s3 bucket
  packages/amplify-cli-core/src/__tests__/hooks/hooksExecutor.test.ts
  packages/amplify-cli-core/src/hooks/hooksConstants.ts
  packages/amplify-cli-core/src/hooks/hooksExecutor.ts
  packages/amplify-cli-core/src/hooks/hooksMeta.ts
  packages/amplify-cli/src/commands/push.ts
  packages/amplify-cli/src/display-banner-messages.ts
  packages/amplify-e2e-tests/src/__tests__/hooks.test.ts
  packages/amplify-provider-awscloudformation/src/__tests__/utils/hooks-manager.test.ts
  packages/amplify-provider-awscloudformation/src/attach-backend.js
  packages/amplify-provider-awscloudformation/src/index.ts
  packages/amplify-provider-awscloudformation/src/initialize-env.ts
  packages/amplify-provider-awscloudformation/src/initializer.ts
  packages/amplify-provider-awscloudformation/src/utils/hooks-manager.ts
Labels: coordination-required, do-not-merge

#10720 feat: pretty print cloudformation event logs
  packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/trigger-file-uploader.js
  packages/amplify-category-hosting/lib/S3AndCloudFront/helpers/file-uploader.js
  packages/amplify-cli-npm/index.ts
  packages/amplify-cli/src/commands/env/remove.ts
  packages/amplify-cli/src/extensions/amplify-helpers/delete-project.ts
  packages/amplify-e2e-core/src/categories/api.ts
  packages/amplify-e2e-core/src/init/amplifyPush.ts
  packages/amplify-e2e-core/src/utils/pinpoint.ts
  packages/amplify-prompts/src/__tests__/multibar.test.ts
  packages/amplify-prompts/src/__tests__/progressbar.test.ts
  packages/amplify-prompts/src/__tests__/terminal.test.ts
  packages/amplify-prompts/src/index.ts
  packages/amplify-prompts/src/progressbars/multibar.ts
  packages/amplify-prompts/src/progressbars/progressbar.ts
  packages/amplify-prompts/src/progressbars/spinner.ts
  packages/amplify-prompts/src/progressbars/terminal.ts
  packages/amplify-provider-awscloudformation/src/__tests__/aws-utils/aws-cfn.test.js
  packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn-progress-formatter.ts
  packages/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js
  packages/amplify-provider-awscloudformation/src/aws-utils/aws-s3.ts
  packages/amplify-provider-awscloudformation/src/initializer.ts
  packages/amplify-provider-awscloudformation/src/push-resources.ts
  packages/amplify-provider-awscloudformation/src/upload-appsync-files.js
Labels: do-not-merge

#10946 Reduce Python package size
  packages/amplify-python-function-runtime-provider/src/util/packageUtils.ts
Labels: first-time-contributor
