Repository aws-amplify/amplify-cli, pull requests merged in 2022-11, with the labels that each got.

#11274 feat(cli): add walkthrough for adding a device location tracking resource
  packages/amplify-category-geo/resources/custom-device-location-tracking-resource-handler.js
  packages/amplify-category-geo/src/__tests__/commands/geo/add.test.ts
  packages/amplify-category-geo/src/__tests__/commands/geo/remove.test.ts
  packages/amplify-category-geo/src/__tests__/commands/geo/update.test.ts
  packages/amplify-category-geo/src/__tests__/service-stacks/deviceLocationTrackingStack.test.ts
  packages/amplify-category-geo/src/__tests__/service-utils/resourceUtils.test.ts
  packages/amplify-category-geo/src/__tests__/service-utils/serviceUtils.test.ts
  packages/amplify-category-geo/src/__tests__/service-walkthroughs/deviceLocationTrackerWalkthrough.test.ts
  packages/amplify-category-geo/src/provider-controllers/deviceLocationTracking.ts
  packages/amplify-category-geo/src/provider-controllers/index.ts
  packages/amplify-category-geo/src/service-stacks/deviceLocationTrackingStack.ts
  packages/amplify-category-geo/src/service-utils/constants.ts
  packages/amplify-category-geo/src/service-utils/deviceLocationTrackingConstants.ts
  packages/amplify-category-geo/src/service-utils/deviceLocationTrackingParams.ts
  packages/amplify-category-geo/src/service-utils/deviceLocationTrackingUtils.ts
  packages/amplify-category-geo/src/service-utils/resourceUtils.ts
  packages/amplify-category-geo/src/service-walkthroughs/deviceLocationTrackingWalkthrough.ts
  packages/amplify-category-geo/src/service-walkthroughs/resourceWalkthrough.ts
  packages/amplify-category-geo/src/supportedServices.ts
  packages/amplify-e2e-core/src/categories/geo.ts
  packages/amplify-e2e-core/src/utils/sdk-calls.ts
  packages/amplify-e2e-tests/src/__tests__/geo-add-g.test.ts
  packages/amplify-frontend-javascript/lib/frontend-config-creator.js
  packages/amplify-frontend-javascript/tests/__snapshots__/frontend-config-creator.test.js.snap
  packages/amplify-frontend-javascript/tests/frontend-config-creator.test.js
Labels: geo

#11342 chore: hotpatch commit for data hotpatch
  packages/amplify-cli/package.json
  packages/amplify-container-hosting/package.json
  packages/amplify-graphql-migration-tests/package.json
  packages/amplify-util-mock/package.json
  yarn.lock
Labels: do-not-merge

#11317 chore: update node.js version handling for CLI
  packages/amplify-category-analytics/src/provider-utils/awscloudformation/cloudformation-templates/pinpoint-cloudformation-template.json
  packages/amplify-category-auth/provider-utils/awscloudformation/triggers/CreateAuthChallenge/cloudformation-templates/CreateAuthChallenge.json.ejs
  packages/amplify-category-auth/provider-utils/awscloudformation/triggers/CustomMessage/cloudformation-templates/CustomMessage.json.ejs
  packages/amplify-category-auth/provider-utils/awscloudformation/triggers/DefineAuthChallenge/cloudformation-templates/DefineAuthChallenge.json.ejs
  packages/amplify-category-auth/provider-utils/awscloudformation/triggers/PostAuthentication/cloudformation-templates/PostAuthentication.json.ejs
  packages/amplify-category-auth/provider-utils/awscloudformation/triggers/PostConfirmation/cloudformation-templates/PostConfirmation.json.ejs
  packages/amplify-category-auth/provider-utils/awscloudformation/triggers/PreAuthentication/cloudformation-templates/PreAuthentication.json.ejs
  packages/amplify-category-auth/provider-utils/awscloudformation/triggers/PreSignup/cloudformation-templates/PreSignup.json.ejs
  packages/amplify-category-auth/provider-utils/awscloudformation/triggers/PreTokenGeneration/cloudformation-templates/PreTokenGeneration.json.ejs
  packages/amplify-category-auth/provider-utils/awscloudformation/triggers/VerifyAuthChallengeResponse/cloudformation-templates/VerifyAuthChallengeResponse.json.ejs
  packages/amplify-category-auth/resources/adminAuth/admin-queries-function-template.json.ejs
  packages/amplify-category-auth/resources/cloudformation-templates/auth-template.yml.ejs
  packages/amplify-category-auth/resources/cloudformation-templates/user-pool-group-template.json.ejs
  packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/auth-stack-builder/__snapshots__/auth-stack-transform.test.ts.snap
  packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/auth-stack-builder/__snapshots__/user-pool-group-stack-transform.test.ts.snap
  packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/auth-cognito-stack-builder.ts
  packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/auth-user-pool-group-stack-builder.ts
  packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/generate-auth-trigger-template.ts
  packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/service-walkthroughs/addLayerToFunctionWalkthrough.test.ts
  packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/utils/addLayerToFunctionUtil.test.ts
  packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/utils/lambda-layer-cloud-formation-template.test.ts
  packages/amplify-category-geo/src/__tests__/service-stacks/__snapshots__/mapStack.test.ts.snap
  packages/amplify-category-geo/src/__tests__/service-stacks/__snapshots__/placeIndexStack.test.ts.snap
  packages/amplify-category-geo/src/service-stacks/geofenceCollectionStack.ts
  packages/amplify-category-geo/src/service-stacks/mapStack.ts
  packages/amplify-category-geo/src/service-stacks/placeIndexStack.ts
  packages/amplify-category-interactions/src/provider-utils/awscloudformation/cloudformation-templates/lex-cloudformation-template.json.ejs
  packages/amplify-category-predictions/src/provider-utils/awscloudformation/assets/identifyCFNGenerate.js
  packages/amplify-category-predictions/src/provider-utils/awscloudformation/cloudformation-templates/identify-template.json.ejs
  packages/amplify-category-predictions/src/provider-utils/awscloudformation/triggers/s3/lambda-cloudformation-template.json.ejs
  packages/amplify-category-storage/resources/triggers/dynamoDB/lambda-cloudformation-template.json.ejs
  packages/amplify-category-storage/resources/triggers/s3/lambda-cloudformation-template.json.ejs
  packages/amplify-cli/src/project-config-version-check.ts
  packages/amplify-e2e-tests/src/__tests__/migration/node.function.test.ts
  packages/amplify-nodejs-function-runtime-provider/src/index.ts
  packages/amplify-provider-awscloudformation/resources/update-idp-roles-cfn.json
Labels: semver-major

#11443 chore: update codegen-ui to 2.5.5
  packages/amplify-util-uibuilder/package.json
  packages/amplify-util-uibuilder/src/__tests__/notifyMissingPackages.test.ts
  yarn.lock
Labels: run-e2e
