Repository aws-amplify/amplify-cli, pull requests merged in 2022-10, with the labels that each got.

#11100 Update CircleCI jobs and cache to speed up e2e
  .circleci/config.base.yml
  .circleci/config.yml
Labels: run-e2e

#11028 feat(amplify-util-uibuilder): update codegen-ui with responsive app support
  packages/amplify-util-uibuilder/package.json
  yarn.lock
Labels: run-e2e

#11259 chore: bump version of amplify-codegen to v3.3.1
  packages/amplify-cli/package.json
  packages/amplify-provider-awscloudformation/package.json
  packages/amplify-util-mock/package.json
  yarn.lock
Labels: run-e2e

#10988 feat: migrate CLI to CDK v2
  nx.json
  packages/amplify-category-auth/package.json
  packages/amplify-category-auth/src/__tests__/provider-utils/awscloudformation/auth-stack-builder/auth-cognito-stack-builder.test.ts
  packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/auth-cognito-stack-builder.ts
  packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/auth-stack-transform.ts
  packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/auth-user-pool-group-stack-builder.ts
  packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/stack-synthesizer.ts
  packages/amplify-category-auth/src/provider-utils/awscloudformation/auth-stack-builder/user-pool-group-stack-transform.ts
  packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/generate-auth-trigger-template.ts
  packages/amplify-category-custom/package.json
  packages/amplify-category-custom/resources/cdk-stack.ts.sample
  packages/amplify-category-custom/resources/package.json
  packages/amplify-category-custom/src/__tests__/utils/dependency-management-utils.test.ts
  packages/amplify-category-custom/src/utils/dependency-management-utils.ts
  packages/amplify-category-custom/src/utils/generate-cfn-from-cdk.ts
  packages/amplify-category-geo/package.json
  packages/amplify-category-geo/src/__tests__/service-stacks/__snapshots__/mapStack.test.ts.snap
  packages/amplify-category-geo/src/__tests__/service-stacks/__snapshots__/placeIndexStack.test.ts.snap
  packages/amplify-category-geo/src/__tests__/service-stacks/geofenceCollectionStack.test.ts
  packages/amplify-category-geo/src/__tests__/service-stacks/mapStack.test.ts
  packages/amplify-category-geo/src/__tests__/service-stacks/placeIndexStack.test.ts
  packages/amplify-category-geo/src/service-stacks/baseStack.ts
  packages/amplify-category-geo/src/service-stacks/geofenceCollectionStack.ts
  packages/amplify-category-geo/src/service-stacks/mapStack.ts
  packages/amplify-category-geo/src/service-stacks/placeIndexStack.ts
  packages/amplify-category-geo/src/service-utils/geofenceCollectionUtils.ts
  packages/amplify-category-geo/src/service-utils/mapUtils.ts
  packages/amplify-category-geo/src/service-utils/placeIndexUtils.ts
  packages/amplify-category-storage/package.json
  packages/amplify-category-storage/src/provider-utils/awscloudformation/cdk-stack-builder/ddb-stack-builder.ts
  packages/amplify-category-storage/src/provider-utils/awscloudformation/cdk-stack-builder/ddb-stack-transform.ts
  packages/amplify-category-storage/src/provider-utils/awscloudformation/cdk-stack-builder/s3-stack-builder.ts
  packages/amplify-category-storage/src/provider-utils/awscloudformation/cdk-stack-builder/s3-stack-transform.ts
  packages/amplify-category-storage/src/provider-utils/awscloudformation/cdk-stack-builder/types.ts
  packages/amplify-cli-core/src/category-interfaces/amplify-base-cdk-types.ts
  packages/amplify-cli-core/src/feature-flags/featureFlags.ts
  packages/amplify-cli-extensibility-helper/package.json
  packages/amplify-cli-extensibility-helper/src/types/api/amplify-api-resource-stack-types.ts
  packages/amplify-cli-extensibility-helper/src/types/api/types.ts
  packages/amplify-cli-extensibility-helper/src/types/auth/types.ts
  packages/amplify-cli-extensibility-helper/src/types/project/types.ts
  packages/amplify-cli-extensibility-helper/src/types/storage/types.ts
  packages/amplify-cli/package.json
  packages/amplify-graphql-migration-tests/package.json
  packages/amplify-provider-awscloudformation/package.json
  packages/amplify-provider-awscloudformation/src/__tests__/root-stack-builder/__snapshots__/root-stack-builder.test.ts.snap
  packages/amplify-provider-awscloudformation/src/__tests__/root-stack-builder/root-stack-builder.test.ts
  packages/amplify-provider-awscloudformation/src/__tests__/utils/consolidate-apigw-policies.test.ts
  packages/amplify-provider-awscloudformation/src/network/stack.ts
  packages/amplify-provider-awscloudformation/src/root-stack-builder/root-stack-builder.ts
  packages/amplify-provider-awscloudformation/src/root-stack-builder/root-stack-transform.ts
  packages/amplify-provider-awscloudformation/src/root-stack-builder/stack-synthesizer.ts
  packages/amplify-provider-awscloudformation/src/utils/consolidate-apigw-policies.ts
  yarn.lock
Labels: do-not-merge

#11289 fix: fix typo in cronExpression.ts
  packages/amplify-category-function/src/provider-utils/awscloudformation/utils/cronExpression.ts
Labels: first-time-contributor
