Repository aws-amplify/amplify-cli, pull requests merged in 2023-02, with the labels that each got.

#11923 chore: prepend @aws-amplify to amplify-category-function
  packages/amplify-category-function/API.md
  packages/amplify-category-function/package.json
  packages/amplify-cli/package.json
  packages/amplify-cli/src/__tests__/extensions/amplify-helpers/resource-status.test.ts
  packages/amplify-cli/src/extensions/amplify-helpers/resource-status-data.ts
  packages/amplify-cli/src/extensions/amplify-helpers/update-amplify-meta.ts
  packages/amplify-cli/tests/amplify-helpers/trigger-flow.test.js
  packages/amplify-util-mock/package.json
  packages/amplify-util-mock/src/__tests__/api/lambda-invoke.test.ts
  packages/amplify-util-mock/src/__tests__/api/lambda-trigger-handler.test.ts
  packages/amplify-util-mock/src/__tests__/func/index.test.ts
  packages/amplify-util-mock/src/api/api.ts
  packages/amplify-util-mock/src/api/lambda-arn-to-config.ts
  packages/amplify-util-mock/src/api/lambda-invoke.ts
  packages/amplify-util-mock/src/api/lambda-trigger-handler.ts
  packages/amplify-util-mock/src/func/index.ts
  packages/amplify-util-mock/src/mockAll.ts
  packages/amplify-util-mock/src/storage/storage.ts
  packages/amplify-util-mock/src/utils/lambda/find-lambda-triggers.ts
Labels: dependency-issue

#11930 chore: prepend @aws-amplify to amplify-category-interactions
  packages/amplify-category-interactions/API.md
  packages/amplify-category-interactions/package.json
  packages/amplify-cli/package.json
Labels: dependency-issue

#11926 chore: prepend @aws-amplify to amplify-category-geo
  packages/amplify-category-geo/API.md
  packages/amplify-category-geo/package.json
  packages/amplify-category-geo/src/service-utils/validateGeoJSONObj.ts
  packages/amplify-cli/package.json
Labels: dependency-issue

#11922 chore: prepend @aws-amplify to amplify-category-analytics
  packages/amplify-category-analytics/API.md
  packages/amplify-category-analytics/package.json
  packages/amplify-cli/package.json
Labels: dependency-issue

#11929 chore: prepend aws/amplify to amplify-category-hosting
  packages/amplify-category-hosting/package.json
  packages/amplify-cli/package.json
  packages/amplify-cli/src/__tests__/commands/status.test.ts
  packages/amplify-cli/src/__tests__/extensions/amplify-helpers/mock-plugin-platform.ts
  packages/amplify-cli/src/__tests__/plugin-helpers/platform-health-check.test.ts
Labels: dependency-issue

#10839 fix: block init if amplify app creation fails
  packages/amplify-provider-awscloudformation/src/__tests__/amplify-service-manager.test.ts
  packages/amplify-provider-awscloudformation/src/amplify-service-manager.ts
Labels: semver-major

#11945 chore: prepend @aws-amplify to functions, interactions, geo, hosting, analytics packages
  packages/amplify-category-analytics/API.md
  packages/amplify-category-analytics/package.json
  packages/amplify-category-function/API.md
  packages/amplify-category-function/package.json
  packages/amplify-category-geo/API.md
  packages/amplify-category-geo/package.json
  packages/amplify-category-geo/src/service-utils/validateGeoJSONObj.ts
  packages/amplify-category-hosting/package.json
  packages/amplify-category-interactions/API.md
  packages/amplify-category-interactions/package.json
  packages/amplify-cli/package.json
  packages/amplify-cli/src/__tests__/commands/status.test.ts
  packages/amplify-cli/src/__tests__/extensions/amplify-helpers/mock-plugin-platform.ts
  packages/amplify-cli/src/__tests__/extensions/amplify-helpers/resource-status.test.ts
  packages/amplify-cli/src/__tests__/plugin-helpers/platform-health-check.test.ts
  packages/amplify-cli/src/extensions/amplify-helpers/resource-status-data.ts
  packages/amplify-cli/src/extensions/amplify-helpers/update-amplify-meta.ts
  packages/amplify-cli/tests/amplify-helpers/trigger-flow.test.js
  packages/amplify-util-mock/package.json
  packages/amplify-util-mock/src/__tests__/api/lambda-invoke.test.ts
  packages/amplify-util-mock/src/__tests__/api/lambda-trigger-handler.test.ts
  packages/amplify-util-mock/src/__tests__/func/index.test.ts
  packages/amplify-util-mock/src/api/api.ts
  packages/amplify-util-mock/src/api/lambda-arn-to-config.ts
  packages/amplify-util-mock/src/api/lambda-invoke.ts
  packages/amplify-util-mock/src/api/lambda-trigger-handler.ts
  packages/amplify-util-mock/src/func/index.ts
  packages/amplify-util-mock/src/mockAll.ts
  packages/amplify-util-mock/src/storage/storage.ts
  packages/amplify-util-mock/src/utils/lambda/find-lambda-triggers.ts
Labels: dependency-issue

#11796 fix: update to latest version of pkg (#10284)
  .circleci/local_publish_helpers.sh
  package.json
  yarn.lock
Labels: first-time-contributor

#11971 chore: prepend @aws-amplify to dependencies pt. 4
  packages/amplify-app/package.json
  packages/amplify-app/src/index.js
  packages/amplify-cli/package.json
  packages/amplify-cli/src/__tests__/extensions/amplify-helpers/get-frontend-plugins.test.ts
  packages/amplify-cli/src/__tests__/init-steps/s0-analyzeProject.test.ts
  packages/amplify-cli/src/utils/post-install-initialization.ts
  packages/amplify-frontend-android/package.json
  packages/amplify-frontend-flutter/package.json
  packages/amplify-frontend-ios/package.json
  packages/amplify-frontend-javascript/package.json
  packages/amplify-go-function-runtime-provider/API.md
  packages/amplify-go-function-runtime-provider/amplify-plugin.json
  packages/amplify-go-function-runtime-provider/package.json
  packages/amplify-go-function-runtime-provider/src/constants.ts
  packages/amplify-go-function-template-provider/API.md
  packages/amplify-go-function-template-provider/package.json
Labels: dependency-issue

#11972 chore: prepend @aws-amplify to dependencies pt. 7
  packages/amplify-category-auth/package.json
  packages/amplify-category-auth/src/provider-utils/awscloudformation/import/index.ts
  packages/amplify-category-auth/src/provider-utils/awscloudformation/import/types.ts
  packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerMigrationUtils.ts
  packages/amplify-category-storage/package.json
  packages/amplify-category-storage/src/provider-utils/awscloudformation/import/import-dynamodb.ts
  packages/amplify-category-storage/src/provider-utils/awscloudformation/import/import-s3.ts
  packages/amplify-category-storage/src/provider-utils/awscloudformation/import/types.ts
  packages/amplify-cli/package.json
  packages/amplify-cli/src/__tests__/commands/build.test.ts
  packages/amplify-cli/src/extensions/amplify-helpers/root-stack-status.ts
  packages/amplify-cli/src/utils/post-install-initialization.ts
  packages/amplify-provider-awscloudformation/API.md
  packages/amplify-provider-awscloudformation/package.json
  packages/amplify-provider-awscloudformation/src/__tests__/commands/override.test.ts
  packages/amplify-provider-awscloudformation/src/aws-utils/CognitoUserPoolService.ts
  packages/amplify-provider-awscloudformation/src/aws-utils/DynamoDBService.ts
  packages/amplify-provider-awscloudformation/src/aws-utils/IdentityPoolService.ts
  packages/amplify-provider-awscloudformation/src/aws-utils/S3Service.ts
  packages/amplify-python-function-runtime-provider/API.md
  packages/amplify-python-function-runtime-provider/amplify-plugin.json
  packages/amplify-python-function-runtime-provider/package.json
  packages/amplify-python-function-runtime-provider/src/constants.ts
  packages/amplify-python-function-template-provider/API.md
  packages/amplify-python-function-template-provider/package.json
  packages/amplify-util-import/API.md
  packages/amplify-util-import/package.json
  packages/amplify-util-mock/API.md
  packages/amplify-util-mock/package.json
  packages/amplify-util-mock/src/__tests__/api/find-lambda-triggers.test.ts
  packages/amplify-util-mock/src/__tests__/api/lambda-invoke.test.ts
  packages/amplify-util-mock/src/__tests__/utils/lambda/populate-lambda-mock-env-vars.test.ts
  packages/amplify-util-mock/src/utils/lambda/find-lambda-triggers.ts
  packages/amplify-util-mock/src/utils/lambda/populate-lambda-mock-env-vars.ts
Labels: dependency-issue

#11957 chore: prepend @aws-amplify to dependencies pt.5
  packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/utils/buildLayer.test.ts
  packages/amplify-category-function/src/__tests__/provider-utils/awscloudformation/utils/packageLayer.test.ts
  packages/amplify-category-function/src/provider-utils/awscloudformation/utils/layerMigrationUtils.ts
  packages/amplify-category-function/src/provider-utils/awscloudformation/utils/storeResources.ts
  packages/amplify-cli/package.json
  packages/amplify-cli/src/extensions/amplify-helpers/read-breadcrumbs.ts
  packages/amplify-cli/src/utils/post-install-initialization.ts
  packages/amplify-java-function-runtime-provider/API.md
  packages/amplify-java-function-runtime-provider/amplify-plugin.json
  packages/amplify-java-function-runtime-provider/package.json
  packages/amplify-java-function-runtime-provider/src/utils/constants.ts
  packages/amplify-nodejs-function-runtime-provider/API.md
  packages/amplify-nodejs-function-runtime-provider/amplify-plugin.json
  packages/amplify-nodejs-function-runtime-provider/package.json
  packages/amplify-nodejs-function-template-provider/API.md
  packages/amplify-nodejs-function-template-provider/package.json
  packages/amplify-util-mock/package.json
  packages/amplify-util-mock/src/__e2e__/utils/index.ts
Labels: dependency-issue

#11953 chore: prepend @aws-amplify pt.2
  packages/amplify-category-notifications/API.md
  packages/amplify-category-notifications/package.json
  packages/amplify-category-predictions/API.md
  packages/amplify-category-predictions/package.json
  packages/amplify-cli-core/package.json
  packages/amplify-cli-core/src/exitOnNextTick.ts
  packages/amplify-cli-core/src/logger/index.ts
  packages/amplify-cli-logger/API.md
  packages/amplify-cli-logger/package.json
  packages/amplify-cli-logger/src/index.ts
  packages/amplify-cli/API.md
  packages/amplify-cli/package.json
  packages/amplify-cli/src/__tests__/commands/diagnose.test.ts
  packages/amplify-cli/src/__tests__/extensions/amplify-helpers/git-manager.test.ts
  packages/amplify-cli/src/__tests__/flow-report.test.ts
  packages/amplify-cli/src/__tests__/test-aborting.test.ts
  packages/amplify-cli/src/amplify-exception-handler.ts
  packages/amplify-cli/src/commands/diagnose.ts
  packages/amplify-cli/src/conditional-local-logging-init.ts
  packages/amplify-cli/src/domain/amplify-usageData/FlowReport.ts
  packages/amplify-cli/src/extensions/amplify-helpers/git-manager.ts
  packages/amplify-provider-awscloudformation/package.json
  packages/amplify-provider-awscloudformation/src/__tests__/disconnect-dependent-resources/utils.test.ts
  packages/amplify-provider-awscloudformation/src/__tests__/utils/aws-logging.test.ts
  packages/amplify-provider-awscloudformation/src/utils/aws-logger.ts
Labels: dependency-issue

#11898 feat: adding cli options commands hooks
  packages/amplify-cli-core/API.md
  packages/amplify-cli-core/src/__tests__/hooks/hooksExecutor.test.ts
  packages/amplify-cli-core/src/hooks/hooksExecutor.ts
  packages/amplify-cli-core/src/hooks/hooksTypes.ts
Labels: do-not-merge

#11912 chore: preprend @aws-amplify to amplify-app
  packages/amplify-app/package.json
  packages/amplify-cli/package.json
  packages/amplify-cli/src/pre-deployment-pull.ts
Labels: dependency-issue

#12031 chore: prepend @aws-amplify to amplify-app dependency
  packages/amplify-app/package.json
  packages/amplify-cli/package.json
  packages/amplify-cli/src/pre-deployment-pull.ts
Labels: dependency-issue

#12049 chore: prepend @aws-amplify scoping pt 3
  packages/amplify-cli-shared-interfaces/API.md
  packages/amplify-cli-shared-interfaces/package.json
  packages/amplify-cli/API.md
  packages/amplify-cli/package.json
  packages/amplify-cli/src/__tests__/extensions/amplify-helpers/mock-plugin-platform.ts
  packages/amplify-cli/src/__tests__/plugin-helpers/platform-health-check.test.ts
  packages/amplify-cli/src/__tests__/version-manager.test.ts
  packages/amplify-cli/src/domain/amplify-usageData/FlowReport.ts
  packages/amplify-cli/src/domain/amplify-usageData/NoFlowReport.ts
  packages/amplify-cli/src/domain/amplify-usageData/NoUsageData.ts
  packages/amplify-cli/src/domain/amplify-usageData/UsageData.ts
  packages/amplify-cli/src/domain/amplify-usageData/UsageDataPayload.ts
  packages/amplify-cli/src/execution-manager.ts
  packages/amplify-console-hosting/API.md
  packages/amplify-console-hosting/package.json
  packages/amplify-container-hosting/API.md
  packages/amplify-container-hosting/package.json
  packages/amplify-dotnet-function-template-provider/API.md
  packages/amplify-dotnet-function-template-provider/package.json
  packages/amplify-prompts/API.md
  packages/amplify-prompts/package.json
  packages/amplify-prompts/src/prompter.ts
Labels: dependency-issue

#12080 feat: adding sort packages script to package json
  package.json
Labels: dependency-issue

#12042 chore: enable eu-south-1 region
  packages/amplify-e2e-core/src/utils/pinpoint.ts
  packages/amplify-provider-awscloudformation/src/aws-predictions-regions.js
  packages/amplify-provider-awscloudformation/src/aws-regions.js
  packages/amplify-provider-awscloudformation/src/aws-utils/aws-lex.js
  packages/amplify-provider-awscloudformation/src/aws-utils/aws-pinpoint.js
  packages/amplify-provider-awscloudformation/src/utils/admin-helpers.ts
Labels: platform
